# -*- coding: utf-8 -*-
"""config

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jenJiOBf4NCCQ5o5k_EffDEbo9Mu8zDR
"""

weather_api_key="14d74e63ae16c29d1de534c67d90e2fe"
g_key = "AIzaSyDU5H4zlImIQB02ZSMBfo6tOULE3DiFQnE"